### ISSUE TITLE
install aping

### ISSUE THREAD

**Issue by MinhKMA** [zehome/aping#1]
hey, thank for your project aping. How to install aping ???

**Comment by zehome** [comment]
This project is not production ready. Basically, you need to know how to use python 3 and a python source package in order to use it. Sorry.

**Comment by MinhKMA** [comment]
I know python3 but when i run python3 setup.py install fails

**Comment by MinhKMA** [comment]
Please, Can you guide me???

**Comment by MinhKMA** [comment]
i like your idea very much so i hope you to guide to me
